In [1]:
INPUT_SHAPE = (3,3,3)
LEARNING_RATE = 1e-3
EPOCHS = 100
C_PUCT = 4
MCTS_ITERATIONS = 10
DIRICHLET_ALPHA = 0.3
EPSILON = .75
TRAINING_SIZE = 64

In [2]:
import numpy as np
import random
from tqdm import tqdm
import math
import keras
from keras.layers import *
from keras.models import Model
from keras.optimizers import Adam
import keras.utils as utils
from keras.callbacks import LearningRateScheduler

In [3]:
class Game:
    def __init__(self):
        self.board = np.zeros((3,3))
        self.lastmove = None

    def no_legal_moves(self):
        for i in range(3):
            for j in range(3):
                if self.board[i][j] == 0:
                    return False
        return True
    
    def result(self):
        def cross_winner():
            cw = False
            if (self.board[0][0] == self.board[1][1] == self.board[2][2]) and (self.board[0][0] != 0):
                return self.board[0][0]
            if (self.board[0][2] == self.board[1][1] == self.board[2][0]) and (self.board[0][2] != 0):
                return self.board[0][2]
            return 0
        
        def hor_winner():
            for i in range(3):
                if (self.board[i][0] == self.board[i][1] == self.board[i][2]) and (self.board[i][0] != 0):
                    return self.board[i][0]
            return 0

        def ver_winner():
            for i in range(3):
                if (self.board[0][i] == self.board[1][i] == self.board[2][i]) and (self.board[0][i] != 0):
                    return self.board[0][i]
            return 0
        
        cw = cross_winner()
        if cw != 0:
            return cw
        
        hw = hor_winner()
        if hw != 0:
            return hw
        
        vw = ver_winner()
        if vw != 0:
            return vw

        return 0

    def is_game_over(self):
        return self.result() != 0 or self.no_legal_moves()

    def copy(self):
        g = Game()
        g.lastmove = self.lastmove
        for i in range(3):
            for j in range(3):
                g.board[i][j] = self.board[i][j]
        return g

    def legal_moves(self):
        lm = []
        for i in range(3):
            for j in range(3):
                if self.board[i][j] == 0:
                    lm.append((i, j))
        return lm

    def push(self, action, p):
        if action in self.legal_moves():
            r, c = action
            self.board[r][c] = p
            self.lastmove = p
        else:
            raise Exception("Illegal move exception")
    
    def turn(self):
        return -self.lastmove if self.lastmove != None else 1

In [4]:
def b_to_img(b):
    img = []
    for i in range(3):
        img.append(np.zeros((3,3)))
    
    img = np.asarray(img)

    turn = b.turn()

    for i in range(3):
        for j in range(3):
            if b.board[i][j] == 1:
                img[0][i][j] = 1
                            
            if b.board[i][j] == -1:
                img[1][i][j] = 1
                
            if turn == 1:
                img[2][i][j] = 1
    
    return img

In [5]:
def create_model(conv_size=256, conv_depth=1):
    input_layer = Input(shape=INPUT_SHAPE, name='BoardInput')
    
    x = Conv2D(filters=conv_size, kernel_size=1)(input_layer)
    for _ in range(conv_depth):
        previous = x
        x = Conv2D(filters=conv_size, kernel_size=1)(x)
        x = BatchNormalization(axis=3)(x)
        x = Activation('relu')(x)
        x = Conv2D(filters=conv_size, kernel_size=1)(x)
        x = BatchNormalization(axis=3)(x)
        x = Add()([x, previous])
        x = Activation('relu')(x)
    x = Flatten()(x)
    
    x = Dense(1028, activation='relu')(x)
    x = Dropout(.3)(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(.3)(x)

    policy = Dense(9, activation='softmax', name='policy')(x)
    value = Dense(1, activation='tanh', name='value')(x)

    model = Model(inputs=input_layer, outputs=[policy, value])
    
    model.compile(loss=['categorical_crossentropy', 'mean_squared_error'], optimizer=Adam(lr=LEARNING_RATE))

    return model

In [6]:
model = create_model()
#model = keras.models.load_model('model.h5')

In [7]:
class MCTSNode:
    def __init__(self, state, prior_probability, action=None, parent=None):
        self.state = state
        self.prior_probability = prior_probability
        
        self.action = action
        self.parent = parent

        self.children = []

        self.N = 0
        self.W = 0
        self.Q = 0

    def is_root(self):
        return self.parent == None

    def is_leaf(self):
        return len(self.children) == 0

    def set_children(self, nnet=model):
        if not self.state.is_game_over():
            prior_probs = nnet.predict(b_to_img(self.state).reshape(1,3,3,3))[0][0].reshape(3,3)
            
            lm = self.state.legal_moves()
            
            for i in range(len(prior_probs)):
                for j in range(len(prior_probs[i])):
                    if (i, j) not in lm:
                        prior_probs[i][j] = 0
            prior_probs = prior_probs.reshape((9,))
            s = np.sum(prior_probs)
            for i in range(len(prior_probs)):
                prior_probs[i] = prior_probs[i] / s        
            prior_probs = prior_probs.reshape((3,3))
            
            noise = np.random.dirichlet(np.ones(len(lm))*DIRICHLET_ALPHA)
            
            for i in range(len(lm)):
                b = self.state.copy()
                b.push(lm[i], b.turn())
                r, c = lm[i][0], lm[i][1]
                pp = prior_probs[r][c]
                pp_n = EPSILON*pp + (1-EPSILON)*noise[i]
                act = lm[i]
                par = self
                self.children.append(MCTSNode(b, pp_n, action=act, parent=par))
    
    def get_ucb(self, nnet):
        return self.Q + C_PUCT * self.prior_probability * (math.sqrt(self.parent.N) / (1 + self.N))

    def select_child(self, nnet=model):
        if not self.state.is_game_over():
            scores = [i.get_ucb(nnet) for i in self.children]
            return self.children[np.argmax(scores)]
        else:
            return self

    def rollout(self, nnet=model):
        if not self.state.is_game_over():
            result = nnet.predict(b_to_img(self.state).reshape(1,3,3,3))[1][0][0]
        else:
            result = self.state.result()

        curr = self
        while True:
            curr.N += 1
            r = result * -curr.state.turn()
            curr.W += r
            curr.Q = curr.W / curr.N
            if curr.is_root():
                break
            else:
                curr = curr.parent

In [8]:
def model_vs_model(nnet1, nnet2, matches=10):
    p1 = 0
    p2 = 0
    d =  0
    
    nnet1_player = 1
    nnet2_player = -1
    
    for i in range(matches):
        player = 1
        game = Game()
        while not game.is_game_over():
            if player == nnet1_player:
                root = MCTSNode(game, 1)
                for i in range(MCTS_ITERATIONS // 2):
                    iteration_done = False
                    current = root
                    while not iteration_done:
                        if current.is_leaf():
                            if current.N == 0:
                                current.rollout()
                                iteration_done = True
                            elif current.N > 0:
                                current.set_children()
                                current = current.select_child()
                                current.rollout()
                                iteration_done = True
                        else:
                            current = current.select_child()

                visits = [i.N for i in root.children]
                s = sum(visits)
                scores = [i / s for i in visits]
                child = np.random.choice(root.children, p=scores)
                row, col = child.action
                assert(player == game.turn())
                game.push(child.action, player)
        
                player *= -1
            
            elif player == nnet2_player:
                root = MCTSNode(game, 1)
                for i in range(MCTS_ITERATIONS // 2):
                    iteration_done = False
                    current = root
                    while not iteration_done:
                        if current.is_leaf():
                            if current.N == 0:
                                current.rollout()
                                iteration_done = True
                            elif current.N > 0:
                                current.set_children()
                                current = current.select_child()
                                current.rollout()
                                iteration_done = True
                        else:
                            current = current.select_child()

                visits = [i.N for i in root.children]
                s = sum(visits)
                scores = [i / s for i in visits]
                child = np.random.choice(root.children, p=scores)
                row, col = child.action
                assert(player == game.turn())
                game.push(child.action, player)
        
                player *= -1
        
        if game.result() == nnet1_player:
            p1 += 1
        elif game.result() == nnet2_player:
            p2 += 1
        else:
            d += 1
            
        nnet1_player *= -1
        nnet2_player *= -1
        
    print(f'player 1 wins: {p1}')
    print(f'player 2 wins: {p2}')
    print(f'draws: {d}')
        
    if p2 >= matches * 60 / 100:
        return True
    else:
        return False

In [9]:
match_memory = []
results = []

train = True
root = None
x_train = []
policy_train = []
value_train = []

for epoch in tqdm(range(EPOCHS)):
    game = Game()
    root = MCTSNode(game, 1)
    while not game.is_game_over():
        for i in range(MCTS_ITERATIONS):
            iteration_done = False
            current = root
            while not iteration_done:
                if current.is_leaf():
                    if current.N == 0:
                        current.rollout()
                        iteration_done = True
                    elif current.N > 0:
                        current.set_children()
                        current = current.select_child()
                        current.rollout()
                        iteration_done = True
                else:
                    current = current.select_child()

        visits = [i.N for i in root.children]
        s = sum(visits)
        scores = [i/s for i in visits]
        child = np.random.choice(root.children, p=scores)
        root = child
        row, col = child.action
        p = np.zeros((3,3)); p[row][col] = 1; p = p.reshape((9,))
        game.push(child.action, game.turn())
        match_memory.append([b_to_img(root.state), p, None])

    final_result = game.result()
    results.append(final_result)
    for i in range(len(match_memory)):
        if match_memory[i][2] == None:
            match_memory[i][2] = final_result
            
    if len(match_memory) > TRAINING_SIZE:
        random.shuffle(match_memory)
        if train:
            del x_train
            del policy_train
            del value_train
            x_train = []
            policy_train = []
            value_train = []

        for i in range(TRAINING_SIZE):
            x_train.append((match_memory[i][0]))
            policy_train.append(match_memory[i][1])
            value_train.append(match_memory[i][2])

        x_train = np.asarray(x_train)
        policy_train = np.asarray(policy_train)
        value_train = np.asarray(value_train)

        old_weights = model.get_weights()
        old_model = create_model()
        old_model.set_weights(old_weights)

        model.fit(x=x_train, y=[policy_train, value_train], 
                batch_size=32, verbose=1, epochs=4)

        if not model_vs_model(old_model, model):
            train = False
            x_train = list(x_train)
            policy_train = list(policy_train)
            value_train = list(value_train)
            del model
            model = old_model
            print("OLD MODEL WIN")
        else:
            train = True
            del old_weights
            del old_model
            del match_memory
            match_memory = []
            print("NEW MODEL WIN/DRAW")
        print(f'len match memory: {len(match_memory)}')

 10%|█         | 10/100 [00:15<02:12,  1.48s/it]

Epoch 1/4
2/2 [==============================] - 0s 19ms/step - loss: 4.8645 - policy_loss: 3.1694 - value_loss: 1.6951
Epoch 2/4
2/2 [==============================] - 0s 21ms/step - loss: 3.1712 - policy_loss: 2.0903 - value_loss: 1.0809
Epoch 3/4
2/2 [==============================] - 0s 22ms/step - loss: 2.2130 - policy_loss: 1.6834 - value_loss: 0.5296
Epoch 4/4
2/2 [==============================] - 0s 27ms/step - loss: 2.0058 - policy_loss: 1.4662 - value_loss: 0.5396


 11%|█         | 11/100 [00:28<07:13,  4.87s/it]

player 1 wins: 6
player 2 wins: 2
draws: 2
OLD MODEL WIN
len match memory: 70
Epoch 1/4
4/4 [==============================] - 0s 28ms/step - loss: 4.1112 - policy_loss: 2.9154 - value_loss: 1.1957
Epoch 2/4
4/4 [==============================] - 0s 31ms/step - loss: 3.4129 - policy_loss: 2.0384 - value_loss: 1.3745
Epoch 3/4
4/4 [==============================] - 0s 30ms/step - loss: 2.0975 - policy_loss: 1.2270 - value_loss: 0.8705
Epoch 4/4
4/4 [==============================] - 0s 32ms/step - loss: 1.5891 - policy_loss: 0.7330 - value_loss: 0.8560


 12%|█▏        | 12/100 [00:40<10:23,  7.08s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 77
Epoch 1/4
6/6 [==============================] - 0s 30ms/step - loss: 3.8715 - policy_loss: 2.6559 - value_loss: 1.2155
Epoch 2/4
6/6 [==============================] - 0s 34ms/step - loss: 2.3642 - policy_loss: 1.6288 - value_loss: 0.7354
Epoch 3/4
6/6 [==============================] - 0s 32ms/step - loss: 1.4830 - policy_loss: 0.9208 - value_loss: 0.5623
Epoch 4/4
6/6 [==============================] - 0s 32ms/step - loss: 1.0217 - policy_loss: 0.5703 - value_loss: 0.4514


 13%|█▎        | 13/100 [00:55<13:40,  9.43s/it]

player 1 wins: 6
player 2 wins: 3
draws: 1
OLD MODEL WIN
len match memory: 84
Epoch 1/4
8/8 [==============================] - 0s 33ms/step - loss: 5.1483 - policy_loss: 2.7646 - value_loss: 2.3837
Epoch 2/4
8/8 [==============================] - 0s 36ms/step - loss: 3.6751 - policy_loss: 1.2386 - value_loss: 2.4365
Epoch 3/4
8/8 [==============================] - 0s 38ms/step - loss: 2.9213 - policy_loss: 0.4908 - value_loss: 2.4305
Epoch 4/4
8/8 [==============================] - 0s 36ms/step - loss: 2.3151 - policy_loss: 0.2568 - value_loss: 2.0584


 14%|█▍        | 14/100 [01:09<15:29, 10.81s/it]

player 1 wins: 5
player 2 wins: 3
draws: 2
OLD MODEL WIN
len match memory: 91
Epoch 1/4
10/10 [==============================] - 0s 33ms/step - loss: 3.5549 - policy_loss: 2.2951 - value_loss: 1.2598
Epoch 2/4
10/10 [==============================] - 1s 54ms/step - loss: 1.9533 - policy_loss: 1.0696 - value_loss: 0.8837
Epoch 3/4
10/10 [==============================] - 0s 43ms/step - loss: 1.2425 - policy_loss: 0.5398 - value_loss: 0.7027
Epoch 4/4
10/10 [==============================] - 0s 36ms/step - loss: 0.9827 - policy_loss: 0.2613 - value_loss: 0.7215


 15%|█▌        | 15/100 [01:23<16:45, 11.83s/it]

player 1 wins: 5
player 2 wins: 4
draws: 1
OLD MODEL WIN
len match memory: 97
Epoch 1/4
12/12 [==============================] - 0s 37ms/step - loss: 3.6414 - policy_loss: 2.3317 - value_loss: 1.3096
Epoch 2/4
12/12 [==============================] - 0s 38ms/step - loss: 1.6898 - policy_loss: 1.0614 - value_loss: 0.6284
Epoch 3/4
12/12 [==============================] - 0s 38ms/step - loss: 0.8928 - policy_loss: 0.4810 - value_loss: 0.4118
Epoch 4/4
12/12 [==============================] - 0s 37ms/step - loss: 0.5790 - policy_loss: 0.2045 - value_loss: 0.3745


 16%|█▌        | 16/100 [01:38<17:56, 12.82s/it]

player 1 wins: 4
player 2 wins: 5
draws: 1
OLD MODEL WIN
len match memory: 106
Epoch 1/4
14/14 [==============================] - 1s 51ms/step - loss: 3.0606 - policy_loss: 2.0002 - value_loss: 1.0603
Epoch 2/4
14/14 [==============================] - 1s 41ms/step - loss: 1.3802 - policy_loss: 0.8327 - value_loss: 0.5475
Epoch 3/4
14/14 [==============================] - 1s 39ms/step - loss: 0.7891 - policy_loss: 0.3152 - value_loss: 0.4740
Epoch 4/4
14/14 [==============================] - 1s 37ms/step - loss: 0.6647 - policy_loss: 0.2261 - value_loss: 0.4386


 17%|█▋        | 17/100 [01:52<18:18, 13.24s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 111
Epoch 1/4
16/16 [==============================] - 1s 35ms/step - loss: 3.0943 - policy_loss: 2.2120 - value_loss: 0.8823
Epoch 2/4
16/16 [==============================] - 1s 38ms/step - loss: 1.3181 - policy_loss: 0.8025 - value_loss: 0.5156
Epoch 3/4
16/16 [==============================] - 1s 38ms/step - loss: 0.7910 - policy_loss: 0.3620 - value_loss: 0.4291
Epoch 4/4
16/16 [==============================] - 1s 37ms/step - loss: 0.6269 - policy_loss: 0.1669 - value_loss: 0.4601


 18%|█▊        | 18/100 [02:10<20:03, 14.68s/it]

player 1 wins: 3
player 2 wins: 5
draws: 2
OLD MODEL WIN
len match memory: 119
Epoch 1/4
18/18 [==============================] - 1s 43ms/step - loss: 3.1619 - policy_loss: 2.0272 - value_loss: 1.1347
Epoch 2/4
18/18 [==============================] - 1s 43ms/step - loss: 1.2443 - policy_loss: 0.6877 - value_loss: 0.5566
Epoch 3/4
18/18 [==============================] - 1s 44ms/step - loss: 0.7672 - policy_loss: 0.3034 - value_loss: 0.4637
Epoch 4/4
18/18 [==============================] - 1s 52ms/step - loss: 0.5667 - policy_loss: 0.1881 - value_loss: 0.3786


 19%|█▉        | 19/100 [02:27<20:44, 15.37s/it]

player 1 wins: 7
player 2 wins: 3
draws: 0
OLD MODEL WIN
len match memory: 126
Epoch 1/4
20/20 [==============================] - 1s 36ms/step - loss: 3.0292 - policy_loss: 2.0322 - value_loss: 0.9970
Epoch 2/4
20/20 [==============================] - 1s 37ms/step - loss: 1.3468 - policy_loss: 0.7417 - value_loss: 0.6051
Epoch 3/4
20/20 [==============================] - 1s 42ms/step - loss: 0.7447 - policy_loss: 0.2982 - value_loss: 0.4464
Epoch 4/4
20/20 [==============================] - 1s 47ms/step - loss: 0.5046 - policy_loss: 0.1885 - value_loss: 0.3160


 20%|██        | 20/100 [02:44<20:54, 15.68s/it]

player 1 wins: 6
player 2 wins: 2
draws: 2
OLD MODEL WIN
len match memory: 135
Epoch 1/4
22/22 [==============================] - 1s 34ms/step - loss: 2.9737 - policy_loss: 1.7640 - value_loss: 1.2097
Epoch 2/4
22/22 [==============================] - 1s 36ms/step - loss: 1.2102 - policy_loss: 0.5421 - value_loss: 0.6681
Epoch 3/4
22/22 [==============================] - 1s 39ms/step - loss: 0.8001 - policy_loss: 0.2338 - value_loss: 0.5663
Epoch 4/4
22/22 [==============================] - 1s 47ms/step - loss: 0.5133 - policy_loss: 0.1367 - value_loss: 0.3766


 21%|██        | 21/100 [03:01<21:08, 16.06s/it]

player 1 wins: 5
player 2 wins: 4
draws: 1
OLD MODEL WIN
len match memory: 144
Epoch 1/4
24/24 [==============================] - 1s 36ms/step - loss: 2.7283 - policy_loss: 1.8192 - value_loss: 0.9091
Epoch 2/4
24/24 [==============================] - 1s 36ms/step - loss: 1.2974 - policy_loss: 0.5825 - value_loss: 0.7149
Epoch 3/4
24/24 [==============================] - 1s 37ms/step - loss: 0.8890 - policy_loss: 0.2435 - value_loss: 0.6455
Epoch 4/4
24/24 [==============================] - 1s 41ms/step - loss: 0.5656 - policy_loss: 0.1630 - value_loss: 0.4026


 22%|██▏       | 22/100 [03:17<21:06, 16.24s/it]

player 1 wins: 1
player 2 wins: 8
draws: 1
NEW MODEL WIN/DRAW
len match memory: 0


 31%|███       | 31/100 [03:32<02:24,  2.09s/it]

Epoch 1/4
2/2 [==============================] - 0s 22ms/step - loss: 3.8369 - policy_loss: 2.2297 - value_loss: 1.6072
Epoch 2/4
2/2 [==============================] - 0s 24ms/step - loss: 2.7637 - policy_loss: 1.5452 - value_loss: 1.2185
Epoch 3/4
2/2 [==============================] - 0s 28ms/step - loss: 1.7185 - policy_loss: 1.0301 - value_loss: 0.6884
Epoch 4/4
2/2 [==============================] - 0s 29ms/step - loss: 1.2022 - policy_loss: 0.6534 - value_loss: 0.5488


 32%|███▏      | 32/100 [03:44<05:25,  4.79s/it]

player 1 wins: 6
player 2 wins: 4
draws: 0
OLD MODEL WIN
len match memory: 68
Epoch 1/4
4/4 [==============================] - 0s 27ms/step - loss: 3.3034 - policy_loss: 2.1448 - value_loss: 1.1586
Epoch 2/4
4/4 [==============================] - 0s 29ms/step - loss: 1.5760 - policy_loss: 0.9790 - value_loss: 0.5970
Epoch 3/4
4/4 [==============================] - 0s 33ms/step - loss: 1.0624 - policy_loss: 0.4758 - value_loss: 0.5866
Epoch 4/4
4/4 [==============================] - 0s 32ms/step - loss: 0.7843 - policy_loss: 0.3493 - value_loss: 0.4350


 33%|███▎      | 33/100 [03:58<08:34,  7.68s/it]

player 1 wins: 4
player 2 wins: 2
draws: 4
OLD MODEL WIN
len match memory: 76
Epoch 1/4
6/6 [==============================] - 0s 48ms/step - loss: 2.9989 - policy_loss: 1.9210 - value_loss: 1.0780
Epoch 2/4
6/6 [==============================] - 0s 43ms/step - loss: 1.2826 - policy_loss: 0.5793 - value_loss: 0.7033
Epoch 3/4
6/6 [==============================] - 0s 33ms/step - loss: 0.7778 - policy_loss: 0.3457 - value_loss: 0.4321
Epoch 4/4
6/6 [==============================] - 0s 33ms/step - loss: 0.6162 - policy_loss: 0.2818 - value_loss: 0.3343


 34%|███▍      | 34/100 [04:11<10:10,  9.25s/it]

player 1 wins: 5
player 2 wins: 4
draws: 1
OLD MODEL WIN
len match memory: 82
Epoch 1/4
8/8 [==============================] - 0s 31ms/step - loss: 2.4283 - policy_loss: 1.5909 - value_loss: 0.8375
Epoch 2/4
8/8 [==============================] - 0s 33ms/step - loss: 0.9360 - policy_loss: 0.4974 - value_loss: 0.4386
Epoch 3/4
8/8 [==============================] - 0s 34ms/step - loss: 0.5478 - policy_loss: 0.2416 - value_loss: 0.3062
Epoch 4/4
8/8 [==============================] - 0s 35ms/step - loss: 0.3916 - policy_loss: 0.1692 - value_loss: 0.2224


 35%|███▌      | 35/100 [04:25<11:29, 10.61s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 89
Epoch 1/4
10/10 [==============================] - 0s 33ms/step - loss: 2.5551 - policy_loss: 1.6416 - value_loss: 0.9135
Epoch 2/4
10/10 [==============================] - 0s 35ms/step - loss: 1.2241 - policy_loss: 0.4759 - value_loss: 0.7482
Epoch 3/4
10/10 [==============================] - 0s 33ms/step - loss: 0.8931 - policy_loss: 0.1828 - value_loss: 0.7103
Epoch 4/4
10/10 [==============================] - 0s 34ms/step - loss: 0.7616 - policy_loss: 0.0939 - value_loss: 0.6677


 36%|███▌      | 36/100 [04:40<12:44, 11.95s/it]

player 1 wins: 4
player 2 wins: 5
draws: 1
OLD MODEL WIN
len match memory: 95
Epoch 1/4
12/12 [==============================] - 0s 32ms/step - loss: 2.3360 - policy_loss: 1.4451 - value_loss: 0.8909
Epoch 2/4
12/12 [==============================] - 0s 35ms/step - loss: 0.9636 - policy_loss: 0.4693 - value_loss: 0.4943
Epoch 3/4
12/12 [==============================] - 0s 34ms/step - loss: 0.5987 - policy_loss: 0.2189 - value_loss: 0.3798
Epoch 4/4
12/12 [==============================] - 0s 34ms/step - loss: 0.4344 - policy_loss: 0.1523 - value_loss: 0.2822


 37%|███▋      | 37/100 [04:54<13:10, 12.55s/it]

player 1 wins: 2
player 2 wins: 7
draws: 1
NEW MODEL WIN/DRAW
len match memory: 0


 46%|████▌     | 46/100 [05:09<01:54,  2.11s/it]

Epoch 1/4
2/2 [==============================] - 0s 19ms/step - loss: 4.2333 - policy_loss: 3.1978 - value_loss: 1.0355
Epoch 2/4
2/2 [==============================] - 0s 21ms/step - loss: 2.6155 - policy_loss: 1.6727 - value_loss: 0.9428
Epoch 3/4
2/2 [==============================] - 0s 22ms/step - loss: 2.0097 - policy_loss: 0.9586 - value_loss: 1.0512
Epoch 4/4
2/2 [==============================] - 0s 27ms/step - loss: 1.6840 - policy_loss: 0.8057 - value_loss: 0.8782


 47%|████▋     | 47/100 [05:21<04:35,  5.20s/it]

player 1 wins: 2
player 2 wins: 5
draws: 3
OLD MODEL WIN
len match memory: 65
Epoch 1/4
4/4 [==============================] - 0s 28ms/step - loss: 3.1243 - policy_loss: 2.1271 - value_loss: 0.9972
Epoch 2/4
4/4 [==============================] - 0s 29ms/step - loss: 1.9335 - policy_loss: 0.9606 - value_loss: 0.9729
Epoch 3/4
4/4 [==============================] - 0s 32ms/step - loss: 1.0475 - policy_loss: 0.3116 - value_loss: 0.7359
Epoch 4/4
4/4 [==============================] - 0s 30ms/step - loss: 0.9482 - policy_loss: 0.3967 - value_loss: 0.5515


 48%|████▊     | 48/100 [05:34<06:35,  7.60s/it]

player 1 wins: 4
player 2 wins: 4
draws: 2
OLD MODEL WIN
len match memory: 71
Epoch 1/4
6/6 [==============================] - 0s 31ms/step - loss: 2.9543 - policy_loss: 1.8831 - value_loss: 1.0712
Epoch 2/4
6/6 [==============================] - 0s 35ms/step - loss: 1.6085 - policy_loss: 0.6871 - value_loss: 0.9214
Epoch 3/4
6/6 [==============================] - 0s 32ms/step - loss: 1.1361 - policy_loss: 0.3359 - value_loss: 0.8002
Epoch 4/4
6/6 [==============================] - 0s 32ms/step - loss: 0.6958 - policy_loss: 0.1068 - value_loss: 0.5890


 49%|████▉     | 49/100 [05:48<08:01,  9.44s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 78
Epoch 1/4
8/8 [==============================] - 0s 32ms/step - loss: 2.7064 - policy_loss: 1.7561 - value_loss: 0.9503
Epoch 2/4
8/8 [==============================] - 0s 35ms/step - loss: 1.3740 - policy_loss: 0.6015 - value_loss: 0.7725
Epoch 3/4
8/8 [==============================] - 0s 34ms/step - loss: 0.8707 - policy_loss: 0.3932 - value_loss: 0.4775
Epoch 4/4
8/8 [==============================] - 0s 36ms/step - loss: 0.5844 - policy_loss: 0.2054 - value_loss: 0.3790


 50%|█████     | 50/100 [06:02<09:07, 10.95s/it]

player 1 wins: 4
player 2 wins: 5
draws: 1
OLD MODEL WIN
len match memory: 87
Epoch 1/4
10/10 [==============================] - 0s 34ms/step - loss: 2.4427 - policy_loss: 1.6267 - value_loss: 0.8160
Epoch 2/4
10/10 [==============================] - 0s 36ms/step - loss: 1.1062 - policy_loss: 0.5745 - value_loss: 0.5317
Epoch 3/4
10/10 [==============================] - 0s 35ms/step - loss: 0.6221 - policy_loss: 0.2245 - value_loss: 0.3976
Epoch 4/4
10/10 [==============================] - 0s 36ms/step - loss: 0.5076 - policy_loss: 0.1558 - value_loss: 0.3518


 51%|█████     | 51/100 [06:19<10:19, 12.63s/it]

player 1 wins: 4
player 2 wins: 4
draws: 2
OLD MODEL WIN
len match memory: 96
Epoch 1/4
12/12 [==============================] - 0s 32ms/step - loss: 2.4083 - policy_loss: 1.5536 - value_loss: 0.8547
Epoch 2/4
12/12 [==============================] - 0s 36ms/step - loss: 1.0472 - policy_loss: 0.4490 - value_loss: 0.5982
Epoch 3/4
12/12 [==============================] - 0s 34ms/step - loss: 0.7182 - policy_loss: 0.2653 - value_loss: 0.4529
Epoch 4/4
12/12 [==============================] - 0s 36ms/step - loss: 0.5181 - policy_loss: 0.1326 - value_loss: 0.3855


 52%|█████▏    | 52/100 [06:33<10:28, 13.08s/it]

player 1 wins: 7
player 2 wins: 2
draws: 1
OLD MODEL WIN
len match memory: 104
Epoch 1/4
14/14 [==============================] - 1s 50ms/step - loss: 2.2175 - policy_loss: 1.3473 - value_loss: 0.8701
Epoch 2/4
14/14 [==============================] - 1s 38ms/step - loss: 0.9513 - policy_loss: 0.4581 - value_loss: 0.4932
Epoch 3/4
14/14 [==============================] - 1s 36ms/step - loss: 0.6458 - policy_loss: 0.2475 - value_loss: 0.3983
Epoch 4/4
14/14 [==============================] - 1s 39ms/step - loss: 0.5363 - policy_loss: 0.1529 - value_loss: 0.3834


 53%|█████▎    | 53/100 [06:48<10:47, 13.77s/it]

player 1 wins: 4
player 2 wins: 4
draws: 2
OLD MODEL WIN
len match memory: 113
Epoch 1/4
16/16 [==============================] - 1s 33ms/step - loss: 2.4331 - policy_loss: 1.3356 - value_loss: 1.0974
Epoch 2/4
16/16 [==============================] - 1s 43ms/step - loss: 1.1040 - policy_loss: 0.3531 - value_loss: 0.7510
Epoch 3/4
16/16 [==============================] - 1s 44ms/step - loss: 0.7168 - policy_loss: 0.2218 - value_loss: 0.4950
Epoch 4/4
16/16 [==============================] - 1s 36ms/step - loss: 0.4727 - policy_loss: 0.1362 - value_loss: 0.3365


 54%|█████▍    | 54/100 [07:02<10:31, 13.74s/it]

player 1 wins: 4
player 2 wins: 5
draws: 1
OLD MODEL WIN
len match memory: 118
Epoch 1/4
18/18 [==============================] - 1s 35ms/step - loss: 2.1484 - policy_loss: 1.3710 - value_loss: 0.7774
Epoch 2/4
18/18 [==============================] - 1s 36ms/step - loss: 0.8170 - policy_loss: 0.3596 - value_loss: 0.4575
Epoch 3/4
18/18 [==============================] - 1s 35ms/step - loss: 0.5952 - policy_loss: 0.2105 - value_loss: 0.3847
Epoch 4/4
18/18 [==============================] - 1s 36ms/step - loss: 0.4918 - policy_loss: 0.1328 - value_loss: 0.3590


 55%|█████▌    | 55/100 [07:16<10:25, 13.91s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 126
Epoch 1/4
20/20 [==============================] - 1s 34ms/step - loss: 2.0432 - policy_loss: 1.3019 - value_loss: 0.7413
Epoch 2/4
20/20 [==============================] - 1s 35ms/step - loss: 0.8746 - policy_loss: 0.3677 - value_loss: 0.5070
Epoch 3/4
20/20 [==============================] - 1s 35ms/step - loss: 0.6871 - policy_loss: 0.1848 - value_loss: 0.5024
Epoch 4/4
20/20 [==============================] - 1s 49ms/step - loss: 0.6077 - policy_loss: 0.1550 - value_loss: 0.4526


 56%|█████▌    | 56/100 [07:32<10:30, 14.32s/it]

player 1 wins: 5
player 2 wins: 4
draws: 1
OLD MODEL WIN
len match memory: 135
Epoch 1/4
22/22 [==============================] - 1s 35ms/step - loss: 2.0799 - policy_loss: 1.2587 - value_loss: 0.8212
Epoch 2/4
22/22 [==============================] - 1s 36ms/step - loss: 0.9391 - policy_loss: 0.3449 - value_loss: 0.5942
Epoch 3/4
22/22 [==============================] - 1s 35ms/step - loss: 0.6718 - policy_loss: 0.1865 - value_loss: 0.4853
Epoch 4/4
22/22 [==============================] - 1s 36ms/step - loss: 0.6063 - policy_loss: 0.1381 - value_loss: 0.4682


 57%|█████▋    | 57/100 [07:47<10:32, 14.71s/it]

player 1 wins: 5
player 2 wins: 3
draws: 2
OLD MODEL WIN
len match memory: 143
Epoch 1/4
24/24 [==============================] - 1s 34ms/step - loss: 2.0018 - policy_loss: 1.2331 - value_loss: 0.7688
Epoch 2/4
24/24 [==============================] - 1s 35ms/step - loss: 0.9468 - policy_loss: 0.3768 - value_loss: 0.5700
Epoch 3/4
24/24 [==============================] - 1s 35ms/step - loss: 0.7270 - policy_loss: 0.2221 - value_loss: 0.5049
Epoch 4/4
24/24 [==============================] - 1s 37ms/step - loss: 0.6118 - policy_loss: 0.1495 - value_loss: 0.4624


 58%|█████▊    | 58/100 [08:03<10:23, 14.84s/it]

player 1 wins: 7
player 2 wins: 2
draws: 1
OLD MODEL WIN
len match memory: 152
Epoch 1/4
26/26 [==============================] - 1s 35ms/step - loss: 1.9037 - policy_loss: 1.1224 - value_loss: 0.7813
Epoch 2/4
26/26 [==============================] - 1s 36ms/step - loss: 0.7661 - policy_loss: 0.2928 - value_loss: 0.4733
Epoch 3/4
26/26 [==============================] - 1s 36ms/step - loss: 0.5669 - policy_loss: 0.1793 - value_loss: 0.3877
Epoch 4/4
26/26 [==============================] - 1s 36ms/step - loss: 0.5139 - policy_loss: 0.1480 - value_loss: 0.3659


 59%|█████▉    | 59/100 [08:19<10:25, 15.26s/it]

player 1 wins: 3
player 2 wins: 6
draws: 1
NEW MODEL WIN/DRAW
len match memory: 0


 68%|██████▊   | 68/100 [08:34<01:10,  2.21s/it]

Epoch 1/4
2/2 [==============================] - 0s 14ms/step - loss: 4.8915 - policy_loss: 3.2812 - value_loss: 1.6103
Epoch 2/4
2/2 [==============================] - 0s 24ms/step - loss: 3.3013 - policy_loss: 2.0026 - value_loss: 1.2988
Epoch 3/4
2/2 [==============================] - 0s 22ms/step - loss: 2.4126 - policy_loss: 1.3855 - value_loss: 1.0272
Epoch 4/4
2/2 [==============================] - 0s 24ms/step - loss: 1.9254 - policy_loss: 1.1014 - value_loss: 0.8240


 69%|██████▉   | 69/100 [08:45<02:30,  4.84s/it]

player 1 wins: 7
player 2 wins: 2
draws: 1
OLD MODEL WIN
len match memory: 68
Epoch 1/4
4/4 [==============================] - 0s 27ms/step - loss: 3.4019 - policy_loss: 2.1097 - value_loss: 1.2922
Epoch 2/4
4/4 [==============================] - 0s 28ms/step - loss: 2.2127 - policy_loss: 1.3009 - value_loss: 0.9118
Epoch 3/4
4/4 [==============================] - 0s 29ms/step - loss: 1.3191 - policy_loss: 0.5899 - value_loss: 0.7292
Epoch 4/4
4/4 [==============================] - 0s 27ms/step - loss: 1.0673 - policy_loss: 0.4229 - value_loss: 0.6444


 70%|███████   | 70/100 [08:56<03:26,  6.87s/it]

player 1 wins: 5
player 2 wins: 3
draws: 2
OLD MODEL WIN
len match memory: 73
Epoch 1/4
6/6 [==============================] - 0s 28ms/step - loss: 3.6401 - policy_loss: 2.2912 - value_loss: 1.3488
Epoch 2/4
6/6 [==============================] - 0s 30ms/step - loss: 1.7037 - policy_loss: 0.8798 - value_loss: 0.8240
Epoch 3/4
6/6 [==============================] - 0s 31ms/step - loss: 1.0656 - policy_loss: 0.4182 - value_loss: 0.6473
Epoch 4/4
6/6 [==============================] - 0s 31ms/step - loss: 0.6835 - policy_loss: 0.2851 - value_loss: 0.3984


 71%|███████   | 71/100 [09:08<04:04,  8.44s/it]

player 1 wins: 5
player 2 wins: 4
draws: 1
OLD MODEL WIN
len match memory: 80
Epoch 1/4
8/8 [==============================] - 0s 51ms/step - loss: 3.3608 - policy_loss: 2.0518 - value_loss: 1.3090
Epoch 2/4
8/8 [==============================] - 0s 39ms/step - loss: 1.4077 - policy_loss: 0.6537 - value_loss: 0.7540
Epoch 3/4
8/8 [==============================] - 0s 34ms/step - loss: 0.9163 - policy_loss: 0.3567 - value_loss: 0.5595
Epoch 4/4
8/8 [==============================] - 0s 34ms/step - loss: 0.6137 - policy_loss: 0.1457 - value_loss: 0.4680


 72%|███████▏  | 72/100 [09:21<04:31,  9.71s/it]

player 1 wins: 6
player 2 wins: 4
draws: 0
OLD MODEL WIN
len match memory: 85
Epoch 1/4
10/10 [==============================] - 0s 31ms/step - loss: 2.8499 - policy_loss: 1.7702 - value_loss: 1.0796
Epoch 2/4
10/10 [==============================] - 0s 34ms/step - loss: 1.2696 - policy_loss: 0.5639 - value_loss: 0.7057
Epoch 3/4
10/10 [==============================] - 0s 33ms/step - loss: 0.7265 - policy_loss: 0.1757 - value_loss: 0.5508
Epoch 4/4
10/10 [==============================] - 0s 34ms/step - loss: 0.5570 - policy_loss: 0.1231 - value_loss: 0.4339


 73%|███████▎  | 73/100 [09:35<04:56, 10.97s/it]

player 1 wins: 4
player 2 wins: 4
draws: 2
OLD MODEL WIN
len match memory: 90
Epoch 1/4
12/12 [==============================] - 0s 32ms/step - loss: 2.4371 - policy_loss: 1.5085 - value_loss: 0.9286
Epoch 2/4
12/12 [==============================] - 0s 34ms/step - loss: 0.8847 - policy_loss: 0.5306 - value_loss: 0.3541
Epoch 3/4
12/12 [==============================] - 0s 34ms/step - loss: 0.4817 - policy_loss: 0.1858 - value_loss: 0.2959
Epoch 4/4
12/12 [==============================] - 0s 36ms/step - loss: 0.3780 - policy_loss: 0.0850 - value_loss: 0.2931


 74%|███████▍  | 74/100 [09:47<04:56, 11.40s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 95
Epoch 1/4
14/14 [==============================] - 0s 32ms/step - loss: 2.3889 - policy_loss: 1.5149 - value_loss: 0.8740
Epoch 2/4
14/14 [==============================] - 0s 35ms/step - loss: 0.8588 - policy_loss: 0.3881 - value_loss: 0.4707
Epoch 3/4
14/14 [==============================] - 0s 34ms/step - loss: 0.4685 - policy_loss: 0.1315 - value_loss: 0.3370
Epoch 4/4
14/14 [==============================] - 0s 34ms/step - loss: 0.3456 - policy_loss: 0.0723 - value_loss: 0.2733


 75%|███████▌  | 75/100 [10:00<04:50, 11.63s/it]

player 1 wins: 5
player 2 wins: 5
draws: 0
OLD MODEL WIN
len match memory: 100
Epoch 1/4
16/16 [==============================] - 1s 35ms/step - loss: 2.0590 - policy_loss: 1.2562 - value_loss: 0.8028
Epoch 2/4
16/16 [==============================] - 1s 35ms/step - loss: 0.7086 - policy_loss: 0.3256 - value_loss: 0.3830
Epoch 3/4
16/16 [==============================] - 1s 34ms/step - loss: 0.3479 - policy_loss: 0.0858 - value_loss: 0.2622
Epoch 4/4
16/16 [==============================] - 1s 35ms/step - loss: 0.2628 - policy_loss: 0.0627 - value_loss: 0.2001


 76%|███████▌  | 76/100 [10:13<04:50, 12.12s/it]

player 1 wins: 4
player 2 wins: 6
draws: 0
NEW MODEL WIN/DRAW
len match memory: 0


 84%|████████▍ | 84/100 [10:27<00:36,  2.28s/it]

Epoch 1/4
2/2 [==============================] - 0s 16ms/step - loss: 3.7085 - policy_loss: 2.9043 - value_loss: 0.8042
Epoch 2/4
2/2 [==============================] - 0s 22ms/step - loss: 2.2351 - policy_loss: 1.7973 - value_loss: 0.4378
Epoch 3/4
2/2 [==============================] - 0s 21ms/step - loss: 1.3229 - policy_loss: 0.9124 - value_loss: 0.4105
Epoch 4/4
2/2 [==============================] - 0s 26ms/step - loss: 1.1590 - policy_loss: 0.7358 - value_loss: 0.4232


 85%|████████▌ | 85/100 [10:39<01:19,  5.27s/it]

player 1 wins: 3
player 2 wins: 6
draws: 1
NEW MODEL WIN/DRAW
len match memory: 0


 94%|█████████▍| 94/100 [10:53<00:09,  1.61s/it]

Epoch 1/4
2/2 [==============================] - 0s 17ms/step - loss: 2.9474 - policy_loss: 2.0917 - value_loss: 0.8557
Epoch 2/4
2/2 [==============================] - 0s 22ms/step - loss: 1.9628 - policy_loss: 1.2776 - value_loss: 0.6853
Epoch 3/4
2/2 [==============================] - 0s 21ms/step - loss: 1.3616 - policy_loss: 1.0081 - value_loss: 0.3535
Epoch 4/4
2/2 [==============================] - 0s 21ms/step - loss: 0.9420 - policy_loss: 0.7968 - value_loss: 0.1451


 95%|█████████▌| 95/100 [11:04<00:22,  4.57s/it]

player 1 wins: 2
player 2 wins: 7
draws: 1
NEW MODEL WIN/DRAW
len match memory: 0


100%|██████████| 100/100 [11:13<00:00,  6.74s/it]


In [10]:
model.save('model.h5')

In [14]:
# vs random player
nnet_player = 1
player = 1
game = Game()
while not game.is_game_over():
    print(game.board)
    print('\n')
    if player == nnet_player:
        root = MCTSNode(game, 1)
        for i in range(300):
            iteration_done = False
            current = root
            while not iteration_done:
                if current.is_leaf():
                    if current.N == 0:
                        current.rollout()
                        iteration_done = True
                    elif current.N > 0:
                        current.set_children()
                        current = current.select_child()
                        current.rollout()
                        iteration_done = True
                else:
                    current = current.select_child()

        visits = [i.N for i in root.children]
        s = sum(visits)
        scores = [i / s for i in visits]
        child = root.children[np.argmax(visits)]
        row, col = child.action
        assert(player == game.turn())
        game.push(child.action, player)
        player *= -1        
    else:
        game.push(random.choice(game.legal_moves()), player)
        player *= -1

print(game.board)
print('\n')
print('result:', game.result())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


[[ 0.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


[[-1.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]


[[-1.  0.  1.]
 [ 0. -1.  1.]
 [ 0.  0.  1.]]


result: 1.0


In [12]:
# vs human playing first
nnet_player = 1
player = 1
game = Game()
while not game.is_game_over():
    print(game.board)
    print('\n')
    if player == nnet_player:
        root = MCTSNode(game, 1)
        for i in range(300):
            iteration_done = False
            current = root
            while not iteration_done:
                if current.is_leaf():
                    if current.N == 0:
                        current.rollout()
                        iteration_done = True
                    elif current.N > 0:
                        current.set_children()
                        current = current.select_child()
                        current.rollout()
                        iteration_done = True
                else:
                    current = current.select_child()

        visits = [i.N for i in root.children]
        s = sum(visits)
        scores = [i / s for i in visits]
        child = root.children[np.argmax(visits)]
        row, col = child.action
        assert(player == game.turn())
        game.push(child.action, player)
        player *= -1        
    else:
        r = int(input('insert a row: '))
        c = int(input('insert a column: '))
        print('\n')
        assert((r,c) in game.legal_moves())
        game.push((r,c), player)
        player *= -1

print(game.board)
print('\n')
print('result:', game.result())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


insert a row: 0
insert a column: 0


[[-1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


[[-1.  0.  0.]
 [ 1.  0.  1.]
 [ 0.  0.  0.]]


insert a row: 1
insert a column: 1


[[-1.  0.  0.]
 [ 1. -1.  1.]
 [ 0.  0.  0.]]


[[-1.  0.  0.]
 [ 1. -1.  1.]
 [ 0.  0.  1.]]


insert a row: 0
insert a column: 2


[[-1.  0. -1.]
 [ 1. -1.  1.]
 [ 0.  0.  1.]]


[[-1.  0. -1.]
 [ 1. -1.  1.]
 [ 1.  0.  1.]]


insert a row: 2
insert a column: 1


[[-1.  0. -1.]
 [ 1. -1.  1.]
 [ 1. -1.  1.]]


[[-1.  1. -1.]
 [ 1. -1.  1.]
 [ 1. -1.  1.]]


result: 0


In [13]:
# vs human playing second
nnet_player = -1
player = 1
game = Game()
while not game.is_game_over():
    print(game.board)
    print('\n')
    if player == nnet_player:
        root = MCTSNode(game, 1)
        for i in range(300):
            iteration_done = False
            current = root
            while not iteration_done:
                if current.is_leaf():
                    if current.N == 0:
                        current.rollout()
                        iteration_done = True
                    elif current.N > 0:
                        current.set_children()
                        current = current.select_child()
                        current.rollout()
                        iteration_done = True
                else:
                    current = current.select_child()

        visits = [i.N for i in root.children]
        s = sum(visits)
        scores = [i / s for i in visits]
        child = root.children[np.argmax(visits)]
        row, col = child.action
        assert(player == game.turn())
        game.push(child.action, player)
        player *= -1        
    else:
        r = int(input('insert a row: '))
        c = int(input('insert a column: '))
        print('\n')
        assert((r,c) in game.legal_moves())
        game.push((r,c), player)
        player *= -1

print(game.board)
print('\n')
print('result:', game.result())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


insert a row: 0
insert a column: 0


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]


insert a row: 0
insert a column: 2


[[ 1.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]


[[ 1. -1.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]


insert a row: 2
insert a column: 1


[[ 1. -1.  1.]
 [ 0. -1.  0.]
 [ 0.  1.  0.]]


[[ 1. -1.  1.]
 [ 0. -1.  0.]
 [-1.  1.  0.]]


insert a row: 1
insert a column: 2


[[ 1. -1.  1.]
 [ 0. -1.  1.]
 [-1.  1.  0.]]


[[ 1. -1.  1.]
 [ 0. -1.  1.]
 [-1.  1. -1.]]


insert a row: 1
insert a column: 0


[[ 1. -1.  1.]
 [ 1. -1.  1.]
 [-1.  1. -1.]]


result: 0
